-- Schema Postgres (modo WEB — várias congregações no mesmo banco).
--
-- Duas famílias de tabelas:
--
--   GLOBAIS  — congregações, usuários, sessões, solicitações de acesso.
--              Não pertencem a nenhuma congregação; o acesso é controlado
--              pelo código da aplicação.
--
--   DA CONGREGAÇÃO — pessoas, horários, escala, histórico. Toda linha carrega
--              `congregacao_id` e o isolamento é imposto pelo PRÓPRIO BANCO,
--              via Row Level Security, e não por um WHERE que alguém possa
--              esquecer de escrever. A aplicação declara a congregação da
--              transação com `set_config('app.congregacao_id', ...)`; as
--              políticas abaixo fazem o resto.
--
-- Por que RLS e não filtro no código: são ~160 consultas em SQL cru herdadas
-- da versão desktop. Uma única sem filtro vazaria dados de uma congregação
-- para outra. Com RLS, esquecer o filtro devolve zero linhas (falha fechando)
-- em vez de devolver as linhas erradas.

-- === Funções de contexto ===================================================

-- Congregação da transação atual. NULL quando não declarada — e como
-- `coluna = NULL` é NULL (nunca verdadeiro), toda política nega tudo nesse
-- caso. É a garantia de falhar fechando.
CREATE OR REPLACE FUNCTION current_congregacao() RETURNS bigint
LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('app.congregacao_id', true), '')::bigint
$$;

-- Só o painel do super-admin liga isto, e sempre depois de validar a sessão.
CREATE OR REPLACE FUNCTION is_super_admin() RETURNS boolean
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(NULLIF(current_setting('app.super_admin', true), ''), '') = 'on'
$$;


-- === Tabelas globais =======================================================

CREATE TABLE IF NOT EXISTS app_meta (
    chave TEXT PRIMARY KEY,
    valor TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS congregacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    -- identificador curto e estável usado na URL (/c/<slug>/escala)
    slug TEXT NOT NULL UNIQUE,
    cidade TEXT NOT NULL DEFAULT '',
    ativa INTEGER NOT NULL DEFAULT 1,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- sempre gravado em minúsculas (normalizado na aplicação): é a identidade
    -- do login, e "Joao@x.com" e "joao@x.com" precisam ser a mesma pessoa.
    email TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL DEFAULT '',
    -- administra a instalação inteira: aprova solicitações, cria congregações.
    super_admin INTEGER NOT NULL DEFAULT 0,
    ativo INTEGER NOT NULL DEFAULT 1,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    ultimo_acesso_em TIMESTAMPTZ
);

-- A que congregações o usuário pertence e com qual papel em cada uma.
-- ADMIN   — administra a congregação (inclusive aprovar quem pede acesso a ela)
-- EDITOR  — gera e edita escala, cadastra pessoas
-- LEITOR  — só visualiza e exporta
CREATE TABLE IF NOT EXISTS membros (
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    congregacao_id BIGINT NOT NULL REFERENCES congregacoes(id) ON DELETE CASCADE,
    papel TEXT NOT NULL CHECK (papel IN ('ADMIN', 'EDITOR', 'LEITOR')),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, congregacao_id)
);

-- Pedido de acesso feito por quem ainda não tem conta (ou quer entrar em outra
-- congregação). `congregacao_id` preenchido = quer entrar numa congregação que
-- já existe; `congregacao_nome_sugerida` preenchido = está pedindo para criar
-- uma congregação nova.
CREATE TABLE IF NOT EXISTS solicitacoes_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    nome TEXT NOT NULL DEFAULT '',
    congregacao_id BIGINT REFERENCES congregacoes(id) ON DELETE CASCADE,
    congregacao_nome_sugerida TEXT NOT NULL DEFAULT '',
    mensagem TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'PENDENTE'
        CHECK (status IN ('PENDENTE', 'APROVADA', 'RECUSADA')),
    criada_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    decidida_em TIMESTAMPTZ,
    decidida_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    observacao_decisao TEXT NOT NULL DEFAULT ''
);

-- Só um pedido pendente por e-mail/congregação: sem isto, recarregar o
-- formulário enche o painel de aprovação com duplicatas.
CREATE UNIQUE INDEX IF NOT EXISTS idx_solicitacao_pendente_unica
    ON solicitacoes_acesso (email, COALESCE(congregacao_id, 0))
    WHERE status = 'PENDENTE';

-- Sessões ativas. `id` é o SHA-256 do token que vai no cookie — vazamento do
-- banco não entrega sessões utilizáveis.
CREATE TABLE IF NOT EXISTS sessoes (
    id TEXT PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    -- congregação selecionada agora (quem pertence a mais de uma pode trocar)
    congregacao_id BIGINT REFERENCES congregacoes(id) ON DELETE CASCADE,
    criada_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira_em TIMESTAMPTZ NOT NULL,
    user_agent TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_sessoes_usuario ON sessoes (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sessoes_expira ON sessoes (expira_em);

-- Códigos de 6 dígitos do login por e-mail. Guardamos só o hash, pelo mesmo
-- motivo das sessões.
CREATE TABLE IF NOT EXISTS codigos_login (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    codigo_hash TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira_em TIMESTAMPTZ NOT NULL,
    tentativas INTEGER NOT NULL DEFAULT 0,
    usado_em TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_codigos_email ON codigos_login (email, criado_em DESC);


-- === Tabelas da congregação ================================================
-- Todas seguem o mesmo padrão:
--   congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
-- para que os INSERTs herdados do desktop (que não citam a coluna) continuem
-- válidos, e chaves primárias/estrangeiras compostas com congregacao_id para
-- que dois congregações possam usar o mesmo `slot_id` sem colidir.

CREATE TABLE IF NOT EXISTS pessoas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    genero TEXT NOT NULL CHECK (genero IN ('M', 'F')),
    ativo INTEGER NOT NULL DEFAULT 1,
    telefone TEXT,
    observacoes TEXT,
    -- cônjuge (marido/esposa): permite que a dupla marido+esposa seja uma exceção
    -- válida à regra de mesmo gênero no sorteio. Vínculo simétrico mantido pela
    -- aplicação (setar A->B também seta B->A). NULL = sem cônjuge cadastrado.
    conjuge_id BIGINT,
    -- pode_dirigir: pessoa habilitada a ser dirigente de campo (saída de campo).
    -- Dirigente É uma pessoa (modelo unificado); este flag define o pool de dirigentes.
    pode_dirigir INTEGER NOT NULL DEFAULT 0,
    UNIQUE (congregacao_id, id),
    -- o cônjuge tem de ser da MESMA congregação: a chave composta torna isso
    -- impossível de violar, mesmo com um bug na aplicação. A lista de colunas
    -- no SET NULL (Postgres 15+) é obrigatória aqui: sem ela o banco tentaria
    -- anular também `congregacao_id`, que é NOT NULL.
    FOREIGN KEY (congregacao_id, conjuge_id)
        REFERENCES pessoas (congregacao_id, id) ON DELETE SET NULL (conjuge_id)
);

CREATE INDEX IF NOT EXISTS idx_pessoas_congregacao ON pessoas (congregacao_id);

CREATE TABLE IF NOT EXISTS slot_template (
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    slot_id TEXT NOT NULL,
    dia_semana TEXT NOT NULL,
    periodo TEXT NOT NULL CHECK (periodo IN ('MANHA', 'TARDE')),
    local TEXT NOT NULL,
    ordem INTEGER NOT NULL,
    requer_dirigente INTEGER NOT NULL DEFAULT 0,
    vigencia_inicio TEXT NOT NULL,
    vigencia_fim TEXT,
    ativo INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (congregacao_id, slot_id)
);

CREATE TABLE IF NOT EXISTS disponibilidades (
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    pessoa_id BIGINT NOT NULL,
    slot_id TEXT NOT NULL,
    ativo INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (congregacao_id, pessoa_id, slot_id),
    FOREIGN KEY (congregacao_id, pessoa_id) REFERENCES pessoas (congregacao_id, id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, slot_id) REFERENCES slot_template (congregacao_id, slot_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_disponibilidades_slot ON disponibilidades (congregacao_id, slot_id);

CREATE TABLE IF NOT EXISTS fixos (
    fixo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    slot_id TEXT NOT NULL,
    pessoa_id_1 BIGINT NOT NULL,
    pessoa_id_2 BIGINT,
    vigencia_inicio TEXT NOT NULL,
    vigencia_fim TEXT,
    ativo INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (congregacao_id, slot_id) REFERENCES slot_template (congregacao_id, slot_id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, pessoa_id_1) REFERENCES pessoas (congregacao_id, id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, pessoa_id_2) REFERENCES pessoas (congregacao_id, id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_fixos_slot ON fixos (congregacao_id, slot_id);

CREATE TABLE IF NOT EXISTS bloqueios (
    bloqueio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    data_inicio TEXT NOT NULL,
    data_fim TEXT NOT NULL,
    motivo TEXT,
    ativo INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_bloqueios_congregacao ON bloqueios (congregacao_id);

-- Tabela legada: o modelo atual é "dirigente É uma pessoa" (pessoas.pode_dirigir).
-- Mantida porque `_migrar_dirigentes_para_pessoas` converte bancos antigos e
-- porque bancos desktop importados ainda podem trazê-la preenchida.
CREATE TABLE IF NOT EXISTS dirigentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    ativo INTEGER NOT NULL DEFAULT 1,
    UNIQUE (congregacao_id, id)
);

CREATE TABLE IF NOT EXISTS dirigentes_disponibilidade (
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    dirigente_id BIGINT NOT NULL,
    slot_id TEXT NOT NULL,
    PRIMARY KEY (congregacao_id, dirigente_id, slot_id),
    FOREIGN KEY (congregacao_id, dirigente_id) REFERENCES dirigentes (congregacao_id, id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, slot_id) REFERENCES slot_template (congregacao_id, slot_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS historico_carrinho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    data TEXT NOT NULL,
    slot_id TEXT NOT NULL,
    pessoa_id_1 BIGINT,
    pessoa_id_2 BIGINT,
    origem TEXT NOT NULL CHECK (
        origem IN ('FIXO', 'SORTEIO', 'FALLBACK_PAR_REPETIDO', 'FALLBACK_DUPLICADO', 'MANUAL', 'VAZIO')
    ),
    mes_referencia TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('RASCUNHO', 'FECHADO')),
    FOREIGN KEY (congregacao_id, slot_id) REFERENCES slot_template (congregacao_id, slot_id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, pessoa_id_1) REFERENCES pessoas (congregacao_id, id) ON DELETE SET NULL (pessoa_id_1),
    FOREIGN KEY (congregacao_id, pessoa_id_2) REFERENCES pessoas (congregacao_id, id) ON DELETE SET NULL (pessoa_id_2)
);

CREATE INDEX IF NOT EXISTS idx_hist_carrinho_mes ON historico_carrinho (congregacao_id, mes_referencia);
CREATE INDEX IF NOT EXISTS idx_hist_carrinho_pessoa1 ON historico_carrinho (congregacao_id, pessoa_id_1);
CREATE INDEX IF NOT EXISTS idx_hist_carrinho_pessoa2 ON historico_carrinho (congregacao_id, pessoa_id_2);

CREATE TABLE IF NOT EXISTS historico_dirigentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    data TEXT NOT NULL,
    slot_id TEXT NOT NULL,
    dirigente_id BIGINT,
    mes_referencia TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('RASCUNHO', 'FECHADO')),
    FOREIGN KEY (congregacao_id, slot_id) REFERENCES slot_template (congregacao_id, slot_id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, dirigente_id) REFERENCES dirigentes (congregacao_id, id) ON DELETE SET NULL (dirigente_id)
);

CREATE INDEX IF NOT EXISTS idx_hist_dirigentes_mes ON historico_dirigentes (congregacao_id, mes_referencia);

-- === Saída de campo ========================================================
-- Saída de campo é uma entidade SEPARADA do carrinho: dias e períodos são
-- livremente configuráveis por congregação. Sorteia 1 dirigente (pessoa com
-- pode_dirigir=1) por saída/dia. Um dirigente designado numa saída no período
-- P do dia D fica bloqueado no carrinho no mesmo P/D.

CREATE TABLE IF NOT EXISTS saida_campo_template (
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    saida_id TEXT NOT NULL,
    dia_semana TEXT NOT NULL,
    periodo TEXT NOT NULL CHECK (periodo IN ('MANHA', 'TARDE')),
    local TEXT NOT NULL DEFAULT '',
    ordem INTEGER NOT NULL,
    vigencia_inicio TEXT NOT NULL,
    vigencia_fim TEXT,
    ativo INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (congregacao_id, saida_id)
);

CREATE TABLE IF NOT EXISTS saida_disponibilidade (
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    pessoa_id BIGINT NOT NULL,
    saida_id TEXT NOT NULL,
    PRIMARY KEY (congregacao_id, pessoa_id, saida_id),
    FOREIGN KEY (congregacao_id, pessoa_id) REFERENCES pessoas (congregacao_id, id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, saida_id) REFERENCES saida_campo_template (congregacao_id, saida_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_saida_disp_saida ON saida_disponibilidade (congregacao_id, saida_id);

CREATE TABLE IF NOT EXISTS historico_saidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    data TEXT NOT NULL,
    saida_id TEXT NOT NULL,
    dirigente_id BIGINT,
    mes_referencia TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('RASCUNHO', 'FECHADO')),
    FOREIGN KEY (congregacao_id, saida_id) REFERENCES saida_campo_template (congregacao_id, saida_id) ON DELETE CASCADE,
    FOREIGN KEY (congregacao_id, dirigente_id) REFERENCES pessoas (congregacao_id, id) ON DELETE SET NULL (dirigente_id)
);

CREATE INDEX IF NOT EXISTS idx_hist_saidas_mes ON historico_saidas (congregacao_id, mes_referencia);
CREATE INDEX IF NOT EXISTS idx_hist_saidas_dirigente ON historico_saidas (congregacao_id, dirigente_id);

-- Configurações gerais da congregação (chave/valor):
-- nome_congregacao, idioma (ver app/i18n.py), wizard_concluido ("0"/"1").
CREATE TABLE IF NOT EXISTS configuracoes (
    congregacao_id BIGINT NOT NULL DEFAULT current_congregacao()
        REFERENCES congregacoes(id) ON DELETE CASCADE,
    chave TEXT NOT NULL,
    valor TEXT NOT NULL,
    PRIMARY KEY (congregacao_id, chave)
);


-- === Row Level Security ====================================================
-- Uma política por tabela da congregação, todas iguais: a linha só existe para
-- quem declarou aquela congregação na transação.
--
-- FORCE é o detalhe que faz a diferença: a aplicação conecta como DONA das
-- tabelas, e o dono normalmente ignora RLS. Com FORCE, a política vale também
-- para ela — que é justamente de quem queremos nos proteger, já que é o código
-- da aplicação que pode ter uma consulta sem filtro.
--
-- Checagens de integridade referencial (FK, unicidade) passam por cima de RLS
-- por definição no Postgres, então as chaves compostas continuam funcionando.

DO $$
DECLARE
    tabela text;
BEGIN
    FOREACH tabela IN ARRAY ARRAY[
        'pessoas', 'slot_template', 'disponibilidades', 'fixos', 'bloqueios',
        'dirigentes', 'dirigentes_disponibilidade', 'historico_carrinho',
        'historico_dirigentes', 'saida_campo_template', 'saida_disponibilidade',
        'historico_saidas', 'configuracoes'
    ] LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tabela);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', tabela);
        EXECUTE format('DROP POLICY IF EXISTS isolamento_congregacao ON %I', tabela);
        EXECUTE format(
            'CREATE POLICY isolamento_congregacao ON %I
                 USING (congregacao_id = current_congregacao() OR is_super_admin())
                 WITH CHECK (congregacao_id = current_congregacao() OR is_super_admin())',
            tabela
        );
    END LOOP;
END $$;
